### ISSUE TITLE
Changing group used - multivariate analyses

### ISSUE THREAD

**Issue by adamsorbie** [pcastellanoescuder/POMA#2]
Hey, 

I have a metadata file with multiple different variables, but I can't seem to figure out how i can run a PCA or PLS-DA using anything but the first column in the metadata table. Is this even possible? I noticed in the documentation it states that the first column must be the group, in this case do I have to shift the column order if i want to look at another group?  

Adam

**Comment by pcastellanoescuder** [comment]
Hi Adam!

Exactly. Currently, `PomaMultivariate()` function takes the first metadata file column as study group. If you want to explore another different variable as a group, you should switch the column order of metadata file and place this new variable in the first column.

I am working on being able to explore all the variables in the metadata file as the main study variables without having to change the order of the columns but this will still take a little...

I think the easiest way to do this right now is to switch columns once the `MSnSet` object has been created. Example using the POMA st000284 demo data in the case you want to use "gender" as the study group variable:

```{r}
Biobase::pData(object) <- Biobase::pData(object) %>% 
  dplyr::relocate(gender)
```

**Comment by adamsorbie** [comment]
Ah ok, thanks for your help.
