### ISSUE TITLE
Potential bug in PCA plot

### ISSUE THREAD

**Issue by adamsorbie** [pcastellanoescuder/POMA#3]
Hi, 

When running  ```PomaMultivariate(pre_processed, method = "pca")``` I get the following error ```Error in data.frame(pca_res$x, Groups = Y) : 
  arguments imply differing number of rows: 0, 17```. 

Do you have any idea why this might be? It doesn't seem to be a problem for any other function so I wondered if it was maybe a bug in the newest version. 

Below is the console printout from the input file 

```
MSnSet (storageMode: lockedEnvironment)
assayData: 730 features, 17 samples 
  element names: exprs 
protocolData: none
phenoData
  sampleNames: CB41 CB42 ... CB54 (17 total)
  varLabels: Group sample_weight dir_inf_vol indir_inf_vol
  varMetadata: labelDescription
featureData: none
experimentData: use 'experimentData(object)'
Annotation:  
- - - Processing information - - -
Imputed (knn): Tue May 04 15:30:11 2021 
Normalised (log_pareto): Tue May 04 15:30:38 2021 
Outliers removed (euclidean and median): Tue May 04 15:33:08 2021 
 MSnbase version: 2.16.1
```

**Comment by pcastellanoescuder** [comment]
Hi @adamsorbie!

Thanks for reporting. I noticed this error a few weeks ago. It is produced by an update of the mixOmics package.

It is currently fixed in the latest version of POMA (devel). By now, I recommend using the GitHub version of POMA (and update mixOmics) until the release of the new version of Bioconductor 3.13 in late May.

Hope it works for you:)

**Comment by adamsorbie** [comment]
Yeah that works great thanks! One other thing, I was trying out the pomaEDA function (which is great btw), but I'm just wondering if there's any way to save the output to the working directory? Currently it saves in the poma subfolder in my R lib.

**Comment by pcastellanoescuder** [comment]
Unfortunately this is not yet available... I know it is a bit awkward and of course it is something that needs to be improved. However, I don't think it will be ready for the next Bioconductor release this month... I will try to fix it ASAP in the development version of POMA! Thank you very much for your comments and welcome to contribute if you want :)
