### ISSUE TITLE
Volcano plots

### ISSUE THREAD

**Issue by rfilipesoares** [pcastellanoescuder/POMA#4]
When I have more than two groups in a proteomics experiment, how can I select or enter the group I want to plot in the volcano plot in the vignette?

**Comment by pcastellanoescuder** [comment]
Hi @rfilipesoares !

Unfortunately, POMA does not yet allow you to select the interest groups (if there are more than two) and visualize them.

The easiest option right now is to create a MSnSet subset with your interest groups and then plot them. Try this:

``` r
st000284_subset <- st000284[, colnames(st000284)[st000284@phenoData@data$factors %in% c("CRC", "Healthy")]]

st000284_subset %>%
  PomaVolcano(labels = TRUE)
```

**Comment by rfilipesoares** [comment]
Hi,

I have tried what you suggested below, however it still comes up with an error that my data has more than 2 groups.
***@***.***

Can you please help me with this?

Thank you in advance for your help.
Renata

**Comment by pcastellanoescuder** [comment]
Hi, 

The example dataset `ST000284` also has more than two groups and works fine. 

What version of POMA are you using? Can you provide a reproducible example?

**Comment by rfilipesoares** [comment]
Hi,

That is strange.
The version of POMA I am using is 1.2.0.
Here is what I see in the MSn subset:
***@***.***

***@***.***

When I try to plot the volcano plot with the vignette you sent:
***@***.***

I do not mind to share the MSn subset with you, but how can I share it with you.

Thank you in advance for your help.
Renata

**Comment by pcastellanoescuder** [comment]
Hi Renata,

I can't see your message well and I don't see the error that POMA is giving you.

You can send me the MSnSet object as a .Rda file to my mail `polcaes@gmail.com` and I will try to help.

Maybe it's better to send me a subset of your object/data (where all the study groups are represented) or an anonymized version of it (just in case it's sensitive data).
